# Generated by Django 3.2 on 2023-12-04 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patient.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.IntegerField(unique=True)),
                ('files', models.FileField(upload_to=patient.models.user_directory_path)),
                ('date', models.CharField(max_length=30)),
                ('type_test', models.TextField()),
                ('out_test', models.TextField()),
                ('date_test', models.DateTimeField()),
                ('normal_values', models.CharField(blank=True, max_length=100, null=True)),
                ('national_code', models.CharField(blank=True, default=uuid.uuid1, max_length=10, null=True, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('born', models.IntegerField()),
                ('age', models.IntegerField()),
                ('phone', models.CharField(default='', max_length=12, unique=True)),
                ('marital_status', models.CharField(choices=[('married', 'متاهل'), ('single', 'مجرد')], max_length=30)),
                ('gender', models.CharField(choices=[('woman', 'زن'), ('men', 'مرد')], max_length=30)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
